
kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
  annotations:
    avp.kubernetes.io/path: "credentials/data/app"
type: Opaque
stringData:
  mongo-root-username: <mongo-root-username>
  mongo-root-password: <mongo-root-password>





# apiVersion: v1
# kind: Secret
# metadata:
    # name: mongodb-secret
# type: Opaque
# data:
    # mongo-root-username: dXNlcm5hbWU=
    # mongo-root-password: cGFzc3dvcmQ=



# Install Vault
# helm repo add hashicorp https://helm.releases.hashicorp.com
# helm install vault hashicorp/vault -n vault-demo
# kubectl get all -n vault-demo

# Initial root token = <root token>
# Key 1 = xEAuUg7umxZlyhla95zV8XJmd/s6nf+1i+FLwT0yRBE8
# key 2 = GH75/LjdqhTDxvm6iKLtP2iohKycjFyQnGvdSXMD8SYx
# key 3 = RuvDmR+RjX8Rp1kaajfFf8HoghNOQeAU7DKQe7Ykhbzo

# Install argocd-vault-plugin locally
# wget https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.18.0/argocd-vault-plugin_1.18.0_linux_amd64
# sudo mv argocd-vault-plugin_1.18.0_linux_amd64 argocd-vault-plugin
# chmod +x argocd-vault-plugin
# sudo mv argocd-vault-plugin /usr/local/bin

# sudo vim vault.env
# VAULT_ADDR=http://3.142.212.235:30331/
# VAULT_TOKEN=<root token>
# AVP_TYPE=vault
# AVP_AUTH_TYPE=token

# argocd-vault-plugin generate -c vault.env - < secret.yaml
# cat secret.yaml



# Install vault plugin within argocd
#  kubectl get deploy -n argocd
# kubectl -n argocd edit deploy argocd-repo-server
# kubectl -n argocd get cm
# kubectl -n argocd edit cm argocd-cm
# kubectl -n vault-secret get secret mongodb-secret -o json | jq -r '.data["mongo-root-username"]' | base64 --decode
