apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: spisey/solar-system:8-77a9781bc2d90ae349894b0f1c0693f48a3894c0
        name: solar-system
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
