apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: spisey/solar-system:13-4374b95b607e24532a648429633682d8cfce299f
        name: solar-system
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
