apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: spisey/solar-system:11-17a1e7d7617a8326ff887974f249843d94d24f8d
        name: solar-system
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
