apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: spisey/solar-system:14-916626ddf8ae26a84d433679e574cc25def0bfd5
        name: solar-system
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
