apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: spisey/solar-system:7-0219d0b1bfb7e3d504304778323f1d382039a24a
        name: solar-system
        ports: 
        - containerPort: 80
        envFrom:
          secretRef:
            - mysecret
      imagePullSecrets:
      - name: regcred
