apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system-blue
  labels:
    app: solar-system
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: solar-system
      version: v1 
      color: blue
  template:
    metadata:
      labels:
        app: solar-system
        version: v1 
        color: blue
    spec:
      containers:
        - name: solar-system
          image: chinmayapradhan/solar-system:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
