apiVersion: v1 
kind: Service
metadata:
  name: solar-system-service-blue
spec:
  selector:
    app: solar-system
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort

# modify the selector in live-service from v1 to v2 and apply using kubectl.