apiVersion: v1 
kind: Service
metadata:
  name: solar-system-service-green
spec:
  selector:
    app: solar-system
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort