apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: argocd
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: ArgoApplicationOutOfSync
      repeatInterval: 10m 
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'chinmayapradhan10000@gmail.com'
      from: 'chinmayapradhan10000@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'chinmayapradhan10000@gmail.com'
      authIdentity: 'chinmayapradhan10000@gmail.com'
      authPassword:
        name: gmail-auth
        key: password
