apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gmail-auth
  namespace: argocd
spec:
  encryptedData:
    password: AgAdN5Iy73lTcQbQePOntWY/ITKUd5aVsqxsjbPg0SPvIaI5zYWz8lxQ0frUYfFN4hF02DeAiC19kxiBXI468wYz3GDPu9kOqXxhlxQnPQitQg5kuNvqZ27ElAnSMbOamzin5ItMhEPmt48uFsykogHXXM0AjHDFUWvkjJGmaLZL/aHOQ6YU6bF6LldGGH9r/iC2VS5TVrqU9Rgmr8qvKOMkNUBK8BKft+0eKOCtTuDYwbtEFF6MEPlqvVtv+LMWWN+0GUgTxguab7mwpTIJjnl13yMTFlVa7Ef/FdL8yTCtYAkBj0O+blOtFOj4omRrmZSwvsEttWjh+uCj5pTYk8nKwseSKAIt+pQNH4xS+MzC9bKf+oUE56N0qaThMtRGj4JZ2wpEHNGFsomDzYKgRoUjOMRtpCBcR+VmfjjclImulefErBrzkH+oNoTB3C4gpWWEL8Z74VXd54l/1qSYUkYphUOeBULUNKUrzagSFuk8AK50kDD6PV1f3oneXKQAJC7uM8tH5hiqjla0UOQkW8GrOZaeE/M7s4+mgKjPHff9xM4UT9QtcfM0KzhlskFSRY1trP30hYaLOrbWPcCSiNq1uB/dVTcxlyawHATqESN+ydbalS+hUHke/ZGKDO3RDMQ9/TyQID5uSqw5DLqbMafV0xs/oeZVTixGVRm8yyQ497EBiV4h299u3TmJxrVVOR/9zg9xnekPFpzKimHJfX0nCtr4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gmail-auth
      namespace: argocd
    type: Opaque