apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: bankapp
  annotations:
    avp.kubernetes.io/path: "credentials/data/app"
type: Opaque
stringData:
  db_root_pwd: <db-root-pwd>     # Test@123
  db_name: <db-name>             # bankappdb
  db_user: <db-user>             # root
  