apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: VGVzdEAxMjM=   # Test@123 (base64 encoded)
  mysql-database: YmFua2FwcGRi        # bankappdb (base64 encoded)
  mysql-username: cm9vdA==            # root (base64 encoded)