apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: bankapp
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 156041433917.dkr.ecr.us-east-2.amazonaws.com/bank-app:v1
        ports:
        - containerPort: 8080
        env: 
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_server
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: db_user
              name: db-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_root_pwd
              name: db-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
--- 
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: bankapp
spec:
  selector:
    app: java-app
  ports:
  - port: 80
    targetPort: 8080

